# -*- coding: utf-8 -*-
"""voice_cloning_ai.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12yVQvGq9MsYpi9Sow0lORK2OhzQf43gj
"""

# Commented out IPython magic to ensure Python compatibility.
!pip3 install -U scipy # because the scipy version packaged with colab is not tolerant of misformated WAV files.

!git clone https://github.com/jnordberg/tortoise-tts.git
# %cd tortoise-tts
!pip3 install -r requirements.txt
!pip3 install transformers==4.19.0 einops==0.5.0 rotary_embedding_torch==0.1.5 unidecode==1.3.5
!python3 setup.py install

# Loading necessary libraries
import torch
import torchaudio
import torch.nn as nn
import torch.nn.functional as F

import IPython

from tortoise.api import TextToSpeech
from tortoise.utils.audio import load_audio, load_voice, load_voices

tts = TextToSpeech() # The code provided facilitates the download of all the models utilized by Tortoise from the HuggingFace model hub.

text = "Thanks for reading this article. I hope you learned something." # For testing I've put that text you can change it for your own use case

preset = "high_quality" # Pick a "preset mode" to determine quality. Options: {"ultra_fast", "fast" (default), "standard", "high_quality"}

CUSTOM_VOICE_NAME = "joe" # You upload at least 2 audio clips. They must be a WAV file, 6-10 seconds long.

import os
from google.colab import files

custom_voice_folder = f"tortoise/voices/{CUSTOM_VOICE_NAME}"
os.makedirs(custom_voice_folder)
for i, file_data in enumerate(files.upload().values()):
  with open(os.path.join(custom_voice_folder, f'{i}.wav'), 'wb') as f:
    f.write(file_data)

# Generate speech with the custotm voice.
voice_samples, conditioning_latents = load_voice(CUSTOM_VOICE_NAME)
gen = tts.tts_with_preset(text, voice_samples=voice_samples, conditioning_latents=conditioning_latents,
                          preset=preset)
torchaudio.save(f'generated-{CUSTOM_VOICE_NAME}.wav', gen.squeeze(0).cpu(), 24000)
IPython.display.Audio(f'generated-{CUSTOM_VOICE_NAME}.wav')

